#!/usr/bin/bash/env bash
#error page not found 404
apt-get -y update
apt-get -y install nginx
echo "Holbeton School" > /var/www/html/index.html
echo "Ceci n'est pas une pag page" > /var/www/htmlcustom_404.html
sed -i '/^/tserver_name.*/a error_page 404 /custom_404.html;\nlocation =/custom_404.html {\nroot /var/www/html/;\internal;\n}' /etc/nginx/sites-available/default
service mginx restart
